travis:
  secure:
    BINSTAR_TOKEN: Owl6U5cx73p7SAz2miDlJWRclIb5cerFjYV0zlnZjWUdAtQkz4CTFljE19HSq9S9Jt71Y9fd1plVXCrtrUii5rjtHhbMRmiR6YBxLVNj1Ss3ADMDoAJ/Qa9XUZD1AcLprii7rwCwsAh/SBhhnt2X5iI2jumTkAZgjouEX/bdE0LZLEk/BG2g6tXN/XXl0lHiufJ+3XmejGLQh8eNeldDDNDDpR26ROcvzXRcu8+UhHd8RgUS8azREbrK09lBXzRW5oeFPCjEd8LAp/Hroh9GahSgwd5cb6wNjwCZFBd0N7nYnKcDijjd197sVSCLKTNPpjVTdLWAp6/CkQZBynJLZlQmXd0WzENRrsSBf+izfCYMG1gOFlEMJlHm6zaldPiX66Z5QT73coo24aTM9bWhN8GhAn9s5BVxV7ZNTkyZ/YGVjQfk7jW+Kr8CUc9lzof4dRp/AtYd2AeaGzT2x+MFrAaFip4uWu7UC9JMLfCZM0axUwYtBSbv8g2c9K7D41eiLrZs6PyiFZ5zph5HFMDYmQeCv1hhgbEaku6Pt7Jg8alNkgz3KMYCX8xDkr9zikc/CbW+UAJU4aJLlq9SBe0PVQnRFxHxqO1CgkmTuE4bHBQDns9WE4IYZ8stE++UTUYBLRi0jqgddk0RqGpzXZAe8hu6Lw6ykf+AgdRoXLtUWAM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
