travis:
  secure:
    BINSTAR_TOKEN: j9zwCRzj+GKD5Ktp+kvGT6ox6IlC1R6YRp5SlG9Tr7k84vN9tnAMN5kLZ5M7LFZYQUiuo5TY/NAXhV5fc+OgKJmGto+PbJvqPEqoKnUJofB8brRSQPQA/13ARSQyp4FVSE4DYfpHuzHMoFK/dkva+TkZw8SBHUhAhZF0P39DUW/aEXjHZxAUKpzsYnxF6FJot5IzfIscTBeuv9L1lAoJDPtZUQgnG4un4dwbu5sh290axLGYky8cIudGHk+FctydezazmjDHoIEdVE1kd9zIlJIPJBiDoOJCgqBI7w8WYsAReKbytsn8Eh/4dWCSxd8VdX55/YhLyp120kmqDgiVS9SC+tL5HiSNkLT8/AIBgbSsgS+G7pU6X/21ob3URq3jr9slN0pgfJ8UVbdlfM015U16cBzfbjBCZQ7aKRAyBD62uA740J71wn+rymeY72q16E0A1Hn1m8AkUkQkmzATI1zB4TFqZyrjpsvewvPpeGLdkYCpxxmxVu8K4ebjQziwlsCaB6mNKmTGfmLxOrWzqVP1+Fr6o1LFFv74UR3nlHDf2tyvsVhHCZXaQ3snEHs9VLYBp5sfpAgDN1A5A/QkvTlLXZsc7DMJyCPLxukzyzYtSTFLDgjcOCvCollospWR6IYbBC52xcDIzR5YnK29OoHQE590kefRYRddJRJLyg4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
