travis:
  secure:
    BINSTAR_TOKEN: TpryM4GyFIsk6wHoQ2hCUye04sQWOK1mnqcnuBjZUlL68Zfs4TsE3FyJUCqtzdSCdqWDyiaTIKzVLzLR+vzGYmHWZqB2BIGFu8ISc+BdHnis4JSZtgEWb1mEZSgxsq6TuEerjVMcgobqwMB9w0bGsNYUO6vuJ+qXaRER8+wHCCAjDnY6/CYOSssNjN9NG3Mdizz6nm41Nm4qC4aREeQny/p1Ju2heBo5KkJGHNi3+E3OF2Aolon4Xg2MltK65yYhTp9E1OOu/V1Y2p4Kjw/W2at67iycltPhuV/J9foGKDxQZF7VfexthcXGTpt9K+7aG6Qh0sZLEKBmCMn3ODY0oL2TjvaKF79HhgF75EYPKfEgSfV6Xah2F9hcaZhiOY7YxN4PwlMxIHgKdzqrRjdR28+eE89AdOTS2fIEPYhP1WhdxRszLF6keUOVs4q1ifpoiVzDk86v/V8k5qNpL/O1tOHRg+7ujsTV6fWS5h3nyY6on/AdEIObFaNlcRCyKvh8a7Srg1tXgmxf+6rC7fp6t36e5wBN+wKODgjMTVyU59yEwk6Nk+PzFIpDvmMjy6bySs4a8+XsMkU/PVDAdFqOIgnFqKiHkz3ih0FtCaNPoI9uUijdNrku/7t0ffSRzKoySYHMDei6Hu5cvIcjPoQ9v+i9nT9MDhEXyhyFpqpHP/g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
