travis:
  secure:
    BINSTAR_TOKEN: wqAzuFwAx4WNjBkjhVbhEh3sQTVxvq284ku0GCjO1HnBtIMC1Ib0WDbdV/tM7rbiTf9C6xw0F8xjr+TuqStpxFOJVP9+6dtllReOBk+YZFhhUpJeHewMF00yQ6RMDgaFaMgRsEDRL7j2SS+NSnrFnIFdTobCruq1uGv+GdpYp2FLWmvnMMCKf1/W1gdfWRjxApETmYkeolxLVHbjyYfMHXKICENgZy3Lmom3XEBjBMu3yZO/fOTTHVAFwtTsIIaqmMQMm9pfWAU5fLaxk4O5kgzhcAGfvErT/cMLeDWGdYUrxHteM7coknZQ5AuaITNOrC7GtS2l5KzpyRgh+YDHHy3f/2ZQ2r65BhYURZRQ7cRSDi2lgmxGFaBIgyur8KNH1GPsLRec8rbtZsg4a783o8L3cuRCuvUi4s6ExErsuwJvaLkf2g2rCuNxjI++b/5XPzFKOpoMO3KisNujvztsBF0zRWvKVgiET0CFzy7Q28ZwfH1Se08NLSpMcNwXB4oEA61iH0mWP7Dszeul7MwdTjqRPuPvawfy4OW59BZTXVUY4maazVzLpsITRJ5frEwc4yx4XqF7elht/QDf7HPWaoATLOA3GqwcjGJjJTWxwKsSKFtPfCanRxCu5rmHMHxyQNZ5U7rckfFSE3oh2nn0npRO/HrBdRJwT8mCqfpnQOA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
